export const En = {
  translation: {
    //manger interface
    mangerInterface: "manger interface",
    ManagerPhone: "050-950-5023",
    CompanyPhone: "054-290-2590",
    CompanyEmail: "service@scoopcatering.com",
    sortBy: "SortBy",
    first_name: "First Name",
    last_name: "Last Name",
    gender: "Gender",
    status: "Status",
    birthdate: "Birthdate",
    email: "Email",
    emailConnect: "Email",
    password:"Password",
    passwordConfirmation:"Password Confirmation",
    fullName:"Full Name",
    phoneNumber:"Phone Number",
    name: "Name",
    EventType: "Event type",
    NumberOfGuests: "Number of guests",
    fleshy: "Fleshy",
    milky: "Milky",
    hebrew: "hebrew",
    english: "english",
   
    LogOut:"Log Out",
    loginButton: " Log In",
   
    forgotPassword:`forgot Password?`,
    PasswordReset:`Password Reset`,
    resetPassword:` Reset Password`,
    Register: "Register",
    BookAnEvent: "Book an event",
    gallery: "gallery",
    soon: "comming soon...",
    ContactUs: "Contact Us",
    ContactUsTitle1: "Waiting to hear from you",
    ContactUsTitle2: "Scoop catering team",
    ContactUsMore: "Do you have anything to tell us?",
    shabatMenu: "Shabbat menu",
    passover: "Passover",
    menuTitle: `Hi you have arrived at Scoop's ordering system
        Feel free to choose your favorite food`,
    moreOffers: "You may also want ...",
    EventBooking: "Event booking",
    ScoopCatering: "Scoop Catering",
    OurStory: "Our story",
    OurCustomers: "Our customers",
    OurTeam: "our team",
    Kashrut: "Kashrut",
    ShoppingCart: "Shopping cart",
    payment: "Payment",
    BitInstructions:"Send the amount of the order via Bit to the phone number 050-000-0000 and state your full name as it appears in the order.",
    CheckInstructions:"A check must be prepared for the courier to the order of Scope Catering Ltd.",
    CashInstructions:"Cash, it is advisable to prepare an exact amount in advance. Messengers do not always have excess.",

    checkout: `Checkout`,
    homePageTitel: "Service is our taste",
    MenusForEvents: "Events",
    FoodReadyToShabat: "Shabbat Food",
    Galleries: "Galleries",
    homePageTitel2: "A selection of Shabbat dishes from Scoop Catering",
    SearchResults: "Search Results",
    searchPlaceholder: " Enter product to search",
    searchMessage: "Enter a product to search",
    NoResults: "No Results",
    PreparedFoodCategories: "Prepared food categories",
    ComeAndTasteTheShabbatFood: "Come and taste the Shabbat food",
    ourTeamTitle1: ".At Scoop Catering service is always our top priority",
    ourTeamTitle2: `.We know how special and important your event is to you, which is why it is important to us as well`,
    ourTeamTitle3: `,Our staff at Scoop are always kind and smiling`,
    ourTeamTitle4: `.And will provide your guests with a personal service at a level that will not be forgotten for them`,
    ourTeamTitle5: `.Every event has an "event manager" who makes sure everything is perfect`,
    ourTeamTitle6: `.His job is also to be attentive to your special needs and requests from the beginning of the event to the end`,
    ourTeamTitle7: `.So you can relax and enjoy the event`,
    ourTeamLable2: `Our team at events`,
    ourStoryLable1: `Personal attitude and uncompromising quality are the secret of our success`,

    OurCustomersLable: `Our customers`,

    ourStoryLable2: `Catering owners`,
    ourStoryTitle1: `Started as a small cafe in Beit Shemesh, Gary Shikman and Aryeh Ben Hamo, both with experience`,
    ourStoryTitle2: `Rich in the field of food. Understood that there is a lack of catering places that provide personal service and quality food`,
    ourStoryTitle3: `The new place prospered, and within a year of opening, the partners had already opened the next branch in Efrat. currently`,
    ourStoryTitle4: `Provides the same vision for service and quality, both in the dairy kitchen and in the company's meat kitchen, which provide daily service`,
    ourStoryTitle5: `For companies, institutions, and events of all sizes and budgets`,
    ourStoryTitle6: `.In recent years, Michael Smigel has joined the company in expanding its activities to new audiences outside Gush Etzion and Beit Shemesh`,
    // cart
    emptyCart: `No items yet!`,
    ToTheShoppingCart: `Shopping Cart`,
    ToTheShop: "Back to menu",
    toCheckout: "checkout",
    addProductsLable: `Add products to cart`,
    recommended:`Recommended`,
    outOfStock:`Out Of Stock`,
    SelectAnOption: "Select option",
    addToCart: `Add to cart`,
    addToCartMe: `Add to cart`,
    product1: `Salomon in teriyaki sauce`,
    products: 'products',
    notFoundResults:`not found results for:`,
    scoop: "Scoop",
    OurAddress: "Our Address",
    OpeningHours: "Opening Hours",
    PersonalInformation: "Personal Information",
    EditDetails: "Editing personal details",
    mailAdress: "Email Adress",
    FirstName: "First Name",
    LastName: "Last Name",
    FullName: "Full Name",
    phone: "Phone",
    anotherPhone: "Another Phone",
    address: "Address",
    update: "Update",
    back: "Back",
    OrderSummary: "Order Summary",
    orderComment: "Comments to order",
    hello: "hello",
    connect: "connect",
    Login:"Already registered? connect",
    AlreadyAnAccount:"Already have an account?",
    login:"Login",
    NeedAnAccount:"Need an account?",
    signUp:`Sign Up`,
    signTitle:`Sign Up`,
    Items: "Items",
    InterimTotal: "Interim Total",
    ShippingCost: "Shipping Cost",
    Total: "Total",
    TotalProducts: "Total Products",
    continueToPayment: "Continue to pay",
    deliveryDetails: "Delivery Details",
    AreaOrCity: "Area / city",
    BeitShemesh: "Beit Shemesh",
    GushEtzion: "Gush Etzion",
    Jerusalem: "Jerusalem",
    Modiin: `Modi'in`,
    Raanana: "Raanana",
    AddressPlaceholder:"Enter full address",
    shippingMethod: "Please select shipping method",
    shippingMethod1: "Pickup",
    shippingMethod2: "Home delivery",
    shippingMethod3: "Surprise Orders /Different address",
    InvoiceDetails: "Invoice Details",
    Address: "Address",
    Street: "Street",
    buildingNumber: "building",
    ApartmentNumber: "Apartment",
    sameShippingAndAccountDetails:
      "Shipping details and account details are the same",
    CouponCode: "Coupon Code",
    EnterCouponCode: "Enter coupon code",
    ActivateCoupon: "Activate",
    ActivateCode: "Activate",
    CommentsToOrder: "Comments to order",
    ApprovalOfRegulations: "Approval",
    SaveDetails: "Save details for next time",
    save: "save",
    ContinueToPay: "To Payment",
    CreditCardMessage:`Enter valid CreditCard Number!`,
    // payment page
    FormOfPayment: "Form of payment",
    CardNumber: "Card Number",
    Expiration: "Expiry",
    Month:`Month`,
    Janaury:`Janaury`,
    February:`February`,
    March:`March`,
    April:`April`,
    May:`May`,
    June:`June`,
    July:`July`,
   August:`August`,
  September:`September`,
  October:`October`,
  November:`November`,
  December:`December`,
  
    Year:`Year`,
    CVV: "CVV",
    Id: "ID of the cardholder",
    PaymentsNumber:'Payments Number',
    AdditionalPayment: "Additional payment options",
    AdditionalPayment_: `Bit / paybox / Bank transfer , Cash or check to courier`,
    AdditionalPayment_1: `Contact the office at`,
    AdditionalPayment_2:`need help? `,
    payBox: "paybox",
    Bit: "Bit",
    BankTransfer: "Bank transfer",
    CashORcheck:"Cash or check to courier",
    paymentMethod: "Select Payment",
    TotalPayment: "Total payment",
    MakePayment: "Make payment",
    // shopping cart
    ProductName: "Item Name",
    selectAmount: "Amount",
    Amount: "Amount",
    price: "Price",
    //events page
    eventsTitel: "Event booking",
    eventsLable: "You have an event coming up soon?",
    eventsPiska: `Scoop Catering will be happy to be a culinary part of your important event,Fill in the details here and a Scoop representative will get back to you with a particularly affordable and delicious offer In the best tradition of Scoop, we are waiting for you!`,
    send: "Send",
    Required: "Required fill field",
    EventOption1: "Wedding",
    EventOption2: "Engagement",
    EventOption3: "Brith",
    EventOption4: "Bat Mitzvah",
    EventOption5: "Bar Mitzvah",
    EventOption6: "Sheva Brachos",
    EventOption7: "Party",
    EventOption8: "Company Event",
    EventOption9: "Camp",
    notActiveMsg:"Temporarily inactive",
    //footer section
    lableInput: "Join Updates from Scoop Catering",
    successEmail: "The email was sent successfully",
    placeholderInput: "Your email",
    ChainStores: "Chain stores",
    Events: "Events",
    PrivateEvents: "Private events",
    Menus: "Menus",
    Menu:`Menu`,
    WeddingMenu: "Wedding menu",
    DairyMenu: "Dairy menu",
    BasicDairyMenu: "Basic dairy menu",
    Recommend: "Recommend",
    orders: "Orders",
    OrganizationsAndCompanies: "Organizations and companies",
    OutdoorEvents: "Outdoor events",
    InformationAndArticles: "Information and articles",
    location: "Mitzad",
    Copyright: "all Copyright to Scoop Catering",
    Policy: "Policy",
  },
};
