
export const He = {
    translation: {
        //manger interface
        managerInterface: 'ממשק מנהל',
        ManagerPhone: '050-950-5023',
        CompanyPhone: '054-290-2590',
        CompanyEmail: 'service@scoopcatering.com',
        navBarTitle: 'עובדים ',
        sortBy: ':מיין לפי',
        executePayments: 'ביצוע תשלומים',
        cancelExecutedPayments: 'ביטול ביצוע התשלום',
        mindy: 'מינדי',
        noCheckBoxSelectAlert: 'עליך לבחור עובד אחד או יותר',
        first_name: 'שם פרטי',
        last_name: 'שם משפחה',
        salary: 'משכורת',
        gender: 'מין',
        status: 'מצב',
        birthdate: 'תאריך לידה',
        email: 'כתובת מייל',
        emailConnect: "כתובת מייל...",
        password: "סיסמא",
        passwordConfirmation: `הזן שוב סיסמא`,
        fullName: "שם מלא",
        phoneNumber: "טלפון",
        name: 'שם',
        EventType: 'סוג האירוע',
        NumberOfGuests: 'כמות מוזמנים',
        fleshy: 'בשרי',
        milky: 'חלבי',
        hebrew: 'עברית',
        english: 'אנגלית',
        home: 'בית',
        setting: 'הגדרות',
        employees: 'עובדים',
        search: '...חיפוש',
        searchPlaceholder: ' הזן/י מוצר לחיפוש',
        searchMessage: 'הכנס מוצר לחיפוש',

        loginButton: `כניסה`,
        logout:"התנתק",
        forgotPassword: `שכחתי סיסמא`,
        PasswordReset: `איפוס סיסמא`,
        resetPassword: `אפס סיסמא`,
        Register: 'הרשמה',
        BookAnEvent: 'הזמינו אירוע',
        gallery: 'גלריה',
        soon: '....בקרוב',
        ContactUs: ' צור קשר',
        ContactUsTitle1: 'מחכים לשמוע אותכם',
        ContactUsTitle2: 'צוות סקופ קייטרינג',
        ContactUsMore: 'יש לכם משהו לספר לנו?',
        shabatMenu: 'תפריט שבת',
        passover: 'פסח',
        menuTitle: `היי הגעתם למערכת ההזמנות של סקופ
        מוזמנים לבחור את האוכל האהוב עליכם`,
        moreOffers: 'אולי תרצו גם...',
        EventBooking: 'הזמנת אירועים',
        ScoopCatering: 'סקופ קייטרינג',
        OurStory: ' הסיפור שלנו',
        OurCustomers: ' לקוחותינו',
        OurTeam: ' הצוות שלנו',
        Kashrut: 'כשרות',
        ShoppingCart: 'סל הקניות שלי',
        payment: 'תשלום',
        BitInstructions: "שלחו את סכום ההזמנה דרך ביט לטלפון 050-000-0000 ציינו את שמכם המלא כפי שמופיע בהזמנה.",
        CheckInstructions:`יש להכין עבור השליח צ'ק לפקודת סקופ קייטרינג בע"מ.`,
        CashInstructions: "מזומן ,כדאי להכין מראש סכום מדויק . לשליחים אין תמיד עודף.",
        checkout: 'ביצוע הזמנה',
        homePageTitel: 'שירות זה הטעם שלנו',
        MenusForEvents: 'תפריטים לאירועים',
        FoodReadyToShabat: 'אוכל מוכן לשבת',
        Galleries: 'גלריות',
        homePageTitel2: 'מבחר מאכלי השבת מבית סקופ קייטרינג',
        SearchResults: 'תוצאות חיפוש',
        NoResults: "אין תוצאות",
        // shabatMenu
        PreparedFoodCategories: 'קטגוריות אוכל מוכן',
        ComeAndTasteTheShabbatFood: 'בואו לטעום ממאכלי השבת',
        // ourTeam
        ourTeamTitle1: `בסקופ קייטרינג השירות תמיד נמצא בראש סדר העדיפויות שלנו.`,
        ourTeamTitle2: `אנחנו יודעים עד כמה מיוחד וחשוב לכם האירוע שלכם, ולכן גם לנו הוא חשוב.`,
        ourTeamTitle3: `הצוות שלנו בסקופ תמיד אדיב ומחויך,`,
        ourTeamTitle4: `ויגיש לאורחים שלכם שירות אישי ברמה שלא תישכח עבורם.`,
        ourTeamTitle5: `בכל אירוע יש "מנהל אירועים" הדואג שהכול יהיה מושלם.`,
        ourTeamTitle6: `תפקידו גם להיות קשוב לצרכים והבקשות המיוחדות שלכם מתחילת האירוע ועד סופו.`,
        ourTeamTitle7: `כך שאתם יכולים להיות רגועים וליהנות מהאירוע.`,
        ourTeamLable2: `הצוות שלנו באירועים`,

        // OurCustomers
        OurCustomersLable: `בין לקוחותינו`,

        //  ourStory
        ourStoryLable1: `יחס אישי ואיכות בלי פשרות, הם סוד ההצלחה שלנו`,
        ourStoryLable2: `בעלי הקייטרינג`,
        ourStoryTitle1: ` התחילה כבית קפה קטן בבית שמש, גרי שיקמן ואריה בן חמו, שניהם עם נסיון`,
        ourStoryTitle2: `.עשיר בתחום המזון.הבינו שיש חוסר במקומות הסעדה המספקים שירות אישי ומזון איכותי`,
        ourStoryTitle3: `המקום החדש שגשג, ובתוך שנה מהפתיחה, כבר פתחו השותפים את הסניף הבא ביישוב אפרת. כיום`,
        ourStoryTitle4: `מספק את אותו חזון לשירות ואיכות, גם במטבח החלבי, וגם במטבח הבשרי של החברה, אשר מספקים שירות יום יומי`,
        ourStoryTitle5: `לחברות, מוסדות, ואירועים בכל גודל ותקציב`,
        ourStoryTitle6: `בשנים האחרונות הצטרף מייקל סמייגל כשהוא מרחיב את פעילות החברה לקהלים חדשים מחוץ לגוש עציון ובבית שמש`,
        // cart
        emptyCart: `אין מוצרים בעגלה`,
        ToTheShoppingCart: `לסל הקניות`,
        ToTheShop: 'חזרה לתפריט',
        toCheckout: 'לרכישה',
        addProductsLable: `הוסיפו מוצרים לסל הקניות`,
        recommended: `מומלץ השבוע!`,
        outOfStock: `אזל מהמלאי`,
        SelectAnOption: 'בחר אפשרות',
        addToCart: `הוספה לסל`,
        addToCartMe: `הוסיפו פריטים לסל`,
        product1: 'סלומון ברוטב טריאקי',
        products: 'מוצרים',
        notFoundResults: `לא נמצאו תוצאות עבור:`,
        scoop: 'סקופ',
        OurAddress: 'כתובתינו',
        OpeningHours: 'שעות פתיחה',
        PersonalInformation: 'פרטים אישיים',
        EditDetails: 'עריכת פרטים אישיים',
        mailAdress: 'כתובת מייל',
        FirstName: 'שם פרטי',
        LastName: 'שם משפחה',
        FullName: "שם מלא",
        phone: 'טלפון',
        anotherPhone: 'טלפון נוסף',
        address: 'כתובת',
        update: 'עדכן',
        back: "חזור",
        OrderSummary: 'סיכום הזמנה',
        orderComment: 'הערות להזמנה',
        hello: 'שלום',
        connect: 'התחבר',
        Login: `כבר רשומים? התחברו`,
        AlreadyAnAccount: `כבר רשומים?`,
        login: `התחברות`,
        NeedAnAccount: "משתמש חדש?",
        signUp: `הרשם`,
        signTitle: `רישום משתמש`,
        Items: 'פריטים',
        InterimTotal: 'סך ביניים',
        ShippingCost: 'עלות המשלוח',
        Total: 'סה"כ',
        TotalProducts: 'סה"כ מוצרים',
        continueToPayment: 'המשך לתשלום',
        deliveryDetails: 'פרטי משלוח',
        AreaOrCity: 'אזור/עיר',
        BeitShemesh: 'בית שמש',
        GushEtzion: 'גוש עציון',
        Jerusalem: 'ירושלים',
        Modiin: `מודיעין`,
        Raanana: 'רעננה',
        AddressPlaceholder: `הזן כתובת מלאה`,
        shippingMethod: 'אנא בחר בשיטת משלוח',

        shippingMethod1: 'איסוף עצמי',
        shippingMethod2: 'משלוח עד הבית',
        shippingMethod3: 'הזמנות הפתעה/כתובת שונה',
        InvoiceDetails: 'פרטי חשבונית',
        Address: 'כתובת',
        Street: 'רחוב',
        buildingNumber: 'מס בניין',
        ApartmentNumber: 'מס דירה',
        sameShippingAndAccountDetails: 'פרטי המשלוח ופרטי החשבון זהים',
        CouponCode: 'קוד קופון',
        EnterCouponCode: 'הזינו קוד קופון',
        ActivateCoupon: 'הפעל קופון',
        ActivateCode: 'הפעל קוד',
        CommentsToOrder: 'הערות להזמנה',
        ApprovalOfRegulations: 'אישור',
        SaveDetails: 'אישור כתובת למשלוח',
        save: 'שמור',
        ContinueToPay: 'לתשלום',
        CreditCardMessage: 'הכנס מספר כרטיס אשראי תקין',
        // payment page
        FormOfPayment: 'אמצעי תשלום',
        CardNumber: 'מספר כרטיס',
        Expiration: 'תוקף',
        Month: `חודש`,
        Janaury: `ינואר`,
        February: `פברואר`,
        March: `מרץ`,
        April: `אפריל`,
        May: `מאי`,
        June: `יוני`,
        July: `יולי`,
        August: `אוגוסט`,
        September: `ספטמבר`,
        October: `אוקטובר`,
        November: `נובמבר`,
        December: `דצמבר`,
        Year: `שנה`,
        CVV: '3 ספרות',
        Id: `תעודת זהות בעל הכרטיס`,
        PaymentsNumber: `מס התשלומים`,
        AdditionalPayment: 'אפשרויות תשלום נוספות',
        AdditionalPayment_: `ביט / פייבוקס / העברה בנקאית , מזומן או צק לשליח`,
        AdditionalPayment_1: `פנו אלינו ונשמח לעזור:`,
        AdditionalPayment_2: `צריכים עזרה? `,

        paymentMethod: 'בחר באופן התשלום הרצוי',
        payBox: 'פייבוקס',
        Bit: 'ביט',
        BankTransfer: 'העברה בנקאית',
        CashORcheck: `מזומן או צק לשליח`,
        TotalPayment: 'סה"כ לתשלום',
        MakePayment: 'בצע תשלום',
        // shopping cart
        ProductName: 'שם המוצר',
        selectAmount: 'בחר כמות',
        Amount: 'כמות',
        price: 'מחיר',

        //events page
        eventsTitel: 'הזמנת אירועים',
        eventsLable: '?יש לכם אירוע בקרוב',
        eventsPiska: 'סקופ קייטרינג תשמח להיות חלק קולינרי באירוע החשוב שלכם,מלאו כאן את הפרטים ונציג סקופ יחזור אליכם עם הצעה משתלמת והטעימה במיוחד כמיטב המסורת של סקופ, מחכים לכם',
        send: 'שלח',
        Required: 'שדה מילוי חובה',
        EventOption1: 'חתונה',
        EventOption2: 'אירוסין',
        EventOption3: 'ברית',
        EventOption4: 'בת מצווה',
        EventOption5: 'בר מצווה',
        EventOption6: 'שבע ברכות',
        EventOption7: 'מסיבה',
        EventOption8: 'אירוע חברה',
        EventOption9: 'קאמפ',
        notActiveMsg: "זמנית לא פעיל",
        //footer section
        lableInput: 'הצטרפו לעדכונים מקייטרינג סקופ',
        successEmail: 'המייל נשלח בהצלחה',
        placeholderInput: 'המייל שלך',
        ChainStores: 'חנויות הרשת',
        Events: 'אירועים',
        PrivateEvents: 'אירועים פרטיים',
        Menus: 'תפריטים',
        Menu: `תפריט`,
        WeddingMenu: 'תפריט חתונה',
        DairyMenu: 'תפריט חלבי',
        BasicDairyMenu: 'תפריט חלבי בסיסי',
        Recommend: 'ממליצים',
        orders: 'הזמנות',
        OrganizationsAndCompanies: 'אירגונים וחברות',
        OutdoorEvents: 'אירועי חוץ',
        InformationAndArticles: 'מידע ומאמרים',
        location: 'יישוב מיצד',
        Copyright: 'כל הזכויות שמורות לסקופ קייטרינג',
        Policy: ' תקנון ',




















    }
}